=== jecisc/BazardFac/S6/NAW/TP3/bataille.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT partie (joueur, joueur, tour)> <!-- Une partie a deux joueurs et un numero de tour. -->
<!ELEMENT tour (#PCDATA)> 
<!ELEMENT joueur (nom, grilleA, grilleD, joue)>
<!ELEMENT nom (#PCDATA)>
<!ATTLIST nom id ID #REQUIRED>
<!ELEMENT joue EMPTY> <!-- Permet de savoir si c'est au tour de ce joueur de jouer.-->
<!ATTLIST joue can CDATA #REQUIRED>
<!ELEMENT grilleA (caseA)*> <!-- grille d'attaque -->
<!ELEMENT grilleD (caseD)*> <!--grille de defence -->
<!ELEMENT caseA EMPTY>
<!ATTLIST case col CDATA #REQUIRED lig CDATA #REQUIRED etat CDATA #REQUIRED> <!-- Une case d'attaque a une ligne, une colonne et un etat-->
<!ELEMENT caseD EMPTY>
<!ATTLIST case col CDATA #REQUIRED lig CDATA #REQUIRED etat CDATA #REQUIRED taille_bateau CDATA #REQUIRED> <!--Une case de defence a une ligne, une colonne, un etat et une taille de bateau. Si la taille est 0, il n'y a pas de bateau, sinon la taille permet de savoir quel bateau est la. -->

=== jecisc/BazardFac/S6/NAW/TP3/NAW_bataille_navale/bataille_tour_0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partie SYSTEM "C:\Users\Cyril\TP\NAW\TP1\bataille.dtd">
<partie>
	<joueur>
		<nom id="Joueur1"/>
		<grilleD>
			<caseD col="2" lig="B" etat="0" taille_bateau="5"/>
			<caseD col="3" lig="B" etat="0" taille_bateau="5"/>
			<caseD col="4" lig="B" etat="0" taille_bateau="5"/>
			<caseD col="5" lig="B" etat="0" taille_bateau="5"/>
			<caseD col="6" lig="B" etat="0" taille_bateau="5"/>
			<caseD col="2" lig="F" etat="0" taille_bateau="4"/>
			<caseD col="2" lig="G" etat="0" taille_bateau="4"/>
			<caseD col="2" lig="H" etat="0" taille_bateau="4"/>
			<caseD col="2" lig="I" etat="0" taille_bateau="4"/>
			<caseD col="6" lig="E" etat="0" taille_bateau="3"/>
			<caseD col="7" lig="E" etat="0" taille_bateau="3"/>
			<caseD col="8" lig="E" etat="0" taille_bateau="3"/>
			<caseD col="8" lig="H" etat="0" taille_bateau="2"/>
			<caseD col="8" lig="I" etat="0" taille_bateau="2"/>
			<caseD col="2" lig="D" etat="0" taille_bateau="1"/>
		</grilleD>
		<joue>1</joue>
	</joueur>
	<joueur>
		<nom id="Joueur2"/>
		<grilleD>
			<caseD col="9" lig="B" etat="0" taille_bateau="5"/>
			<caseD col="9" lig="C" etat="0" taille_bateau="5"/>
			<caseD col="9" lig="D" etat="0" taille_bateau="5"/>
			<caseD col="9" lig="E" etat="0" taille_bateau="5"/>
			<caseD col="9" lig="F" etat="0" taille_bateau="5"/>
			<caseD col="3" lig="F" etat="0" taille_bateau="4"/>
			<caseD col="4" lig="F" etat="0" taille_bateau="4"/>
			<caseD col="5" lig="F" etat="0" taille_bateau="4"/>
			<caseD col="6" lig="F" etat="0" taille_bateau="4"/>
			<caseD col="4" lig="C" etat="0" taille_bateau="3"/>
			<caseD col="5" lig="C" etat="0" taille_bateau="3"/>
			<caseD col="6" lig="C" etat="0" taille_bateau="3"/>
			<caseD col="9" lig="H" etat="0" taille_bateau="2"/>
			<caseD col="9" lig="I" etat="0" taille_bateau="2"/>
			<caseD col="5" lig="H" etat="0" taille_bateau="1"/>
		</grilleD>
		<joue>0</joue>
	</joueur>
	<tour nb="0"/>
</partie>
