=== jecisc/BazardFac/S6/NAW/TP5/TP5/NAW_TP5_Bataille_Schema_Element.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2014 rel. 2 sp1 (http://www.altova.com) by USTL (UniversitÃ© des Sciences et Technologies de Lille) -->
<!--W3C Schema generated by XMLSpy v2014 rel. 2 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="partie">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="joueur" minOccurs="2" maxOccurs="2"/>
				<xs:element ref="tour"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tour">
		<xs:complexType>
			<xs:attribute name="nb" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="100"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="joueur">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="grilleD"/>
				<xs:element ref="joue"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="joue">
		<xs:complexType>
			<xs:attribute name="can" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="grilleD">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="caseD"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="caseD">
		<xs:complexType>
			<xs:attribute name="col" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="9"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="lig" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="1"/>
						<xs:enumeration value="A"/>
						<xs:enumeration value="B"/>
						<xs:enumeration value="C"/>
						<xs:enumeration value="D"/>
						<xs:enumeration value="E"/>
						<xs:enumeration value="F"/>
						<xs:enumeration value="G"/>
						<xs:enumeration value="H"/>
						<xs:enumeration value="I"/>
						<xs:enumeration value="J"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="etat" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="3"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="taille_bateau" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="5"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== jecisc/BazardFac/S6/NAW/TP5/TP5/bataille_tour_0.xml
<?xml version="1.0" encoding="UTF-8"?>
<partie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NAW_TP5_Bataille_Schema_Element.xsd">
	<joueur id="Joueur1">
		<grilleD>
			<caseD col="2" lig="B" etat="0" taille_bateau="5"/>
			<caseD col="3" lig="B" etat="0" taille_bateau="5"/>
			<caseD col="4" lig="B" etat="0" taille_bateau="5"/>
			<caseD col="5" lig="B" etat="0" taille_bateau="5"/>
			<caseD col="6" lig="B" etat="0" taille_bateau="5"/>
			<caseD col="2" lig="F" etat="0" taille_bateau="4"/>
			<caseD col="2" lig="G" etat="0" taille_bateau="4"/>
			<caseD col="2" lig="H" etat="0" taille_bateau="4"/>
			<caseD col="2" lig="I" etat="0" taille_bateau="4"/>
			<caseD col="6" lig="E" etat="0" taille_bateau="3"/>
			<caseD col="7" lig="E" etat="0" taille_bateau="3"/>
			<caseD col="8" lig="E" etat="0" taille_bateau="3"/>
			<caseD col="8" lig="H" etat="0" taille_bateau="2"/>
			<caseD col="8" lig="I" etat="0" taille_bateau="2"/>
			<caseD col="2" lig="D" etat="0" taille_bateau="1"/>
		</grilleD>
		<joue can="1"/>
	</joueur>
	<joueur id="Joueur2">
		<grilleD>
			<caseD col="9" lig="B" etat="0" taille_bateau="5"/>
			<caseD col="9" lig="C" etat="0" taille_bateau="5"/>
			<caseD col="9" lig="D" etat="0" taille_bateau="5"/>
			<caseD col="9" lig="E" etat="0" taille_bateau="5"/>
			<caseD col="9" lig="F" etat="0" taille_bateau="5"/>
			<caseD col="3" lig="F" etat="0" taille_bateau="4"/>
			<caseD col="4" lig="F" etat="0" taille_bateau="4"/>
			<caseD col="5" lig="F" etat="0" taille_bateau="4"/>
			<caseD col="6" lig="F" etat="0" taille_bateau="4"/>
			<caseD col="4" lig="C" etat="0" taille_bateau="3"/>
			<caseD col="5" lig="C" etat="0" taille_bateau="3"/>
			<caseD col="6" lig="C" etat="0" taille_bateau="3"/>
			<caseD col="9" lig="H" etat="0" taille_bateau="2"/>
			<caseD col="9" lig="I" etat="0" taille_bateau="2"/>
			<caseD col="5" lig="H" etat="0" taille_bateau="1"/>
		</grilleD>
		<joue can="0"/>
	</joueur>
	<tour nb="0"/>
</partie>
