=== jecisc/BazardFac/S6/NAW/TP1/recette.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT recette (nom_recette, portion, preparation, cuisson, ingredients, guide, (repos?))>
<!ELEMENT ingredients (i)+>
<!ELEMENT i ((nom,nbre)|(nom|poids))>
<!ELEMENT nom_recette (#PCDATA)>
<!ELEMENT portion (#PCDATA)>
<!ELEMENT preparation EMPTY>
<!ATTLIST preparation value CDATA #REQUIRED unit CDATA #REQUIRED>
<!ELEMENT cuisson EMPTY>
<!ATTLIST cuisson value CDATA #REQUIRED unit CDATA #REQUIRED>
<!ELEMENT repos EMPTY>
<!ATTLIST repos value CDATA #REQUIRED unit CDATA #REQUIRED>
<!ELEMENT nom (#PCDATA)>
<!ATTLIST nom id ID #REQUIRED>
<!ELEMENT nbre (#PCDATA)>
<!ELEMENT poids (#PCDATA)>
<!ATTLIST poids unit CDATA #REQUIRED>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT guide (#PCDATA | block| renvoi| repos|strong|cuisson)*>
<!ELEMENT block (#PCDATA | renvoi | repos| strong| cuisson)*>
<!ELEMENT renvoi (#PCDATA)>
<!ATTLIST renvoi ref IDREF #REQUIRED>

=== jecisc/BazardFac/S6/NAW/TP1/recette2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recette SYSTEM "C:\Users\Cyril\TP\NAW\TP1\recette.dtd">
<recette>
	<nom_recette>Oeufs à la coque</nom_recette>
	<portion>4</portion>
	<preparation value="1" unit="min"/>
	<cuisson value="3" unit="min"/>
	<ingredients>
		<i>
			<nom id="ing1">oeufs</nom>
			<nbre>4</nbre>
		</i>
	</ingredients>
	<guide>
Plongez délicatement les <renvoi ref="ing1">oeufs</renvoi> dans de l'eau portée à ébullition. Faîtes reprendre l'ébullition, puis baissez le feu et laissez cuire à petits bouillons pendant <cuisson value="3" unit="min"/> minutes. Égouttez les <renvoi ref="ing1">oeufs</renvoi>, posez-les dans des coquetiers et coupez hortizontalement la partie supérieure pour les déguster.
  </guide>
</recette>
